import React from 'react';
import { ActivityIndicator, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, View, KeyboardAvoidingView, type TextStyle, type ViewStyle } from 'react-native';
import { X, ArrowUpRight, type LucideIcon } from 'lucide-react-native';
import Svg, { Circle, Ellipse, Path, Rect, G, Line } from 'react-native-svg';
import { useSafeAreaInsets } from 'react-native-safe-area-context';

export const C = { bg: '#F8F7F3', paper: '#FFFFFF', ink: '#263D33', muted: '#748077', line: '#E5E8E0', green: '#315B43', lime: '#DAE8C7', pale: '#EEF3E8', orange: '#B95F3F', peach: '#F6E5D9', lilac: '#EAE7F1', red: '#AD4739' };
export const F = { regular: 'DMSans_400Regular', medium: 'DMSans_500Medium', semi: 'DMSans_600SemiBold', bold: 'DMSans_700Bold', serif: 'Lora_400Regular', serifMedium: 'Lora_500Medium' };
export function T({ children, style, muted = false, ...props }: React.ComponentProps<typeof Text> & { muted?: boolean }) { return <Text {...props} style={[{ color: muted ? C.muted : C.ink, fontFamily: F.regular, fontSize: 14, lineHeight: 21 }, style]}>{children}</Text>; }
export function Heading({ children, size = 32, style }: { children: React.ReactNode; size?: number; style?: TextStyle }) { return <T style={[{ fontFamily: F.serif, fontSize: size, lineHeight: size * 1.28, letterSpacing: -0.8 }, style]}>{children}</T>; }
export function Row({ children, style }: { children: React.ReactNode; style?: ViewStyle }) { return <View style={[{ flexDirection: 'row', alignItems: 'center', gap: 12 }, style]}>{children}</View>; }
export function Card({ children, style }: { children: React.ReactNode; style?: ViewStyle }) { return <View style={[{ backgroundColor: C.paper, borderWidth: 1, borderColor: C.line, borderRadius: 22, padding: 24 }, style]}>{children}</View>; }
export function Button({ label, onPress, icon: Icon, variant = 'primary', disabled, busy, style }: { label: string; onPress: () => void; icon?: LucideIcon; variant?: 'primary' | 'secondary' | 'ghost' | 'danger'; disabled?: boolean; busy?: boolean; style?: ViewStyle }) {
  const primary = variant === 'primary';
  const color = primary ? '#fff' : variant === 'danger' ? C.red : C.green;
  return <Pressable accessibilityRole="button" accessibilityLabel={label} disabled={disabled || busy} onPress={onPress} style={({ pressed }) => [{ minHeight: 46, paddingHorizontal: 18, paddingVertical: 12, borderRadius: 13, flexDirection: 'row', gap: 9, alignItems: 'center', justifyContent: 'center', backgroundColor: primary ? C.green : variant === 'secondary' ? C.pale : 'transparent', opacity: disabled ? 0.4 : pressed ? 0.7 : 1 }, style]}>{busy ? <ActivityIndicator color={color} size="small" /> : Icon ? <Icon size={17} color={color} strokeWidth={1.7} /> : null}<T style={{ color, fontFamily: F.semi, fontSize: 13 }}>{label}</T></Pressable>;
}
export function IconButton({ icon: Icon, label, onPress, color = C.ink }: { icon: LucideIcon; label: string; onPress: () => void; color?: string }) { return <Pressable accessibilityRole="button" accessibilityLabel={label} onPress={onPress} style={({ pressed }) => ({ width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', opacity: pressed ? 0.5 : 1 })}><Icon size={20} color={color} strokeWidth={1.6} /></Pressable>; }
export function Pill({ label, color = C.green, background = C.pale }: { label: string; color?: string; background?: string }) { return <View style={{ backgroundColor: background, borderRadius: 20, paddingHorizontal: 10, paddingVertical: 4, alignSelf: 'flex-start' }}><T style={{ color, fontSize: 11, lineHeight: 17, fontFamily: F.medium }}>{label}</T></View>; }
export function Chip({ label, selected, onPress }: { label: string; selected?: boolean; onPress: () => void }) { return <Pressable accessibilityRole="button" accessibilityState={{ selected }} onPress={onPress} style={({ pressed }) => ({ borderRadius: 11, paddingHorizontal: 14, minHeight: 42, justifyContent: 'center', borderWidth: 1, borderColor: selected ? C.green : C.line, backgroundColor: selected ? C.pale : C.paper, opacity: pressed ? 0.6 : 1 })}><T style={{ fontSize: 13, color: selected ? C.green : C.muted, fontFamily: selected ? F.semi : F.regular }}>{label}</T></Pressable>; }
export function Field({ label, value, onChangeText, placeholder, multiline = false, keyboardType, ...rest }: React.ComponentProps<typeof TextInput> & { label?: string }) { return <View style={{ gap: 8 }}>{label && <T style={{ fontSize: 12, fontFamily: F.semi }}>{label}</T>}<TextInput {...rest} accessibilityLabel={label || placeholder} value={value} onChangeText={onChangeText} placeholder={placeholder} placeholderTextColor="#969E94" multiline={multiline} keyboardType={keyboardType} style={[{ fontFamily: F.regular, fontSize: 15, color: C.ink, backgroundColor: C.bg, borderWidth: 1, borderColor: C.line, borderRadius: 13, paddingHorizontal: 15, paddingVertical: 14, minHeight: multiline ? 110 : 48, textAlignVertical: multiline ? 'top' : 'center' }, rest.style]} /></View>; }
export function Notice({ children, warm = false }: { children: React.ReactNode; warm?: boolean }) { return <View style={{ backgroundColor: warm ? '#FBEEE4' : C.pale, borderRadius: 14, padding: 15 }}><T style={{ color: warm ? '#8B583A' : C.green, fontSize: 12, lineHeight: 19 }}>{children}</T></View>; }
export function Sheet({ title, subtitle, onClose, children }: { title: string; subtitle?: string; onClose: () => void; children: React.ReactNode }) {
  const insets = useSafeAreaInsets();
  return <Modal animationType="slide" transparent onRequestClose={onClose}><KeyboardAvoidingView behavior={Platform.OS === 'ios' ? 'padding' : undefined} style={{ flex: 1 }}><View style={{ flex: 1, backgroundColor: '#10281B66', justifyContent: 'center', alignItems: 'center', paddingTop: Math.max(insets.top, 18), paddingBottom: Math.max(insets.bottom, 18), paddingHorizontal: 14 }}><View accessibilityViewIsModal style={{ width: '100%', maxWidth: 610, maxHeight: '100%', backgroundColor: C.paper, borderRadius: 26, overflow: 'hidden' }}><Row style={{ padding: 22, borderBottomWidth: 1, borderBottomColor: C.line }}><View style={{ flex: 1 }}><Heading size={26}>{title}</Heading>{subtitle && <T muted style={{ fontSize: 12, marginTop: 5 }}>{subtitle}</T>}</View><IconButton icon={X} label="Close" onPress={onClose} /></Row><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{ padding: 24, gap: 20 }} showsVerticalScrollIndicator={false}>{children}</ScrollView></View></View></KeyboardAvoidingView></Modal>;
}
export function SectionTitle({ title, action, onPress }: { title: string; action?: string; onPress?: () => void }) { return <Row style={{ justifyContent: 'space-between', marginBottom: 18 }}><T style={{ fontFamily: F.semi, fontSize: 17 }}>{title}</T>{action && <Pressable accessibilityRole="button" onPress={onPress} style={{ padding: 8 }}><Row style={{ gap: 4 }}><T style={{ color: C.green, fontSize: 12 }}>{action}</T><ArrowUpRight size={13} color={C.green} /></Row></Pressable>}</Row>; }

export function Botanical({ size = 190, light = false }: { size?: number; light?: boolean }) {
  return <Svg width={size} height={size} viewBox="0 0 240 240"><Circle cx="128" cy="117" r="95" fill={light ? '#DEE8CA' : '#EAF0DE'} /><Path d="M40 144 C58 206 160 223 207 154" fill="#B4C497" /><Ellipse cx="124" cy="142" rx="85" ry="48" fill="#F8F4E8" /><Ellipse cx="124" cy="136" rx="72" ry="37" fill="#DEE2BF" /><Path d="M59 124 C86 92 108 107 98 136 C88 158 64 147 59 124" fill="#668859" /><Path d="M78 111 Q74 134 92 139 M79 121 L89 117 M83 131 L71 129" stroke="#AAC093" strokeWidth="2.5" fill="none" /><Path d="M97 120 C108 85 139 96 133 125 C129 149 105 147 97 120" fill="#89A472" /><Path d="M115 100 L117 138 M106 113 L117 121 L127 114" stroke="#D0DBB0" strokeWidth="2.5" fill="none" /><Circle cx="147" cy="131" r="19" fill="#D98B62" /><Path d="M133 125 Q148 114 159 130" stroke="#F7BD8D" strokeWidth="3" fill="none" /><Circle cx="119" cy="151" r="13" fill="#E4BC76" /><Circle cx="171" cy="143" r="10" fill="#E8CE95" /><Circle cx="90" cy="149" r="8" fill="#E8CE95" /><Path d="M153 111 C138 74 158 37 180 27 C185 62 161 72 158 88 C185 65 206 81 203 94 C177 109 165 92 159 105" fill="#48734E" /><Path d="M155 114 Q165 57 180 27" stroke="#C1CFA7" strokeWidth="2" fill="none" /><Circle cx="55" cy="70" r="4" fill="#B1C398" /><Circle cx="211" cy="123" r="3" fill="#DDB480" /><Path d="M46 92 L54 92 M50 88 L50 96" stroke="#B1C398" strokeWidth="2" /></Svg>;
}
export function MiniChart({ values, color = C.green, height = 70 }: { values: number[]; color?: string; height?: number }) {
  const width = 240, max = Math.max(5, ...values);
  const points = values.map((v, i) => `${i * width / Math.max(1, values.length - 1)},${height - 8 - (v / max) * (height - 16)}`);
  return <Svg width="100%" height={height} viewBox={`0 0 ${width} ${height}`} preserveAspectRatio="none"><Line x1={0} y1={height - 8} x2={width} y2={height - 8} stroke={C.line} strokeDasharray="4 5" />{values.length > 1 && <><Path d={`M0,${height} L${points.join(' L')} L${width},${height} Z`} fill={C.pale} /><Path d={`M${points.join(' L')}`} stroke={color} strokeWidth="2.5" fill="none" strokeLinejoin="round" /></>}</Svg>;
}
