import React, { useEffect, useMemo, useRef, useState } from 'react';
import { ActivityIndicator, Linking, Platform, Pressable, ScrollView, StatusBar, StyleSheet, Switch, View, useWindowDimensions } from 'react-native';
import { SafeAreaProvider, useSafeAreaInsets } from 'react-native-safe-area-context';
import { useFonts, DMSans_400Regular, DMSans_500Medium, DMSans_600SemiBold, DMSans_700Bold } from '@expo-google-fonts/dm-sans';
import { Lora_400Regular, Lora_500Medium } from '@expo-google-fonts/lora';
import { ArrowDownToLine, ArrowRight, ArrowUpRight, BookOpen, CalendarDays, Camera, Check, ChevronLeft, ChevronRight, CircleHelp, Coffee, Fingerprint, Flower2, Heart, Leaf, LockKeyhole, Plus, Search, Settings2, ShieldCheck, Smile, Sparkles, Sprout, Sun, Trash2, TrendingUp, Upload, Utensils, X } from 'lucide-react-native';
import { C, F, T, Heading, Row, Card, Button, IconButton, Pill, Chip, Field, Notice, Sheet, SectionTitle, Botanical, MiniChart } from './src/components/ui';
import { MealForm, SymptomForm, uid } from './src/components/EntryForms';
import { analyzePatterns, getDemoData, BUILT_IN_SYMPTOMS, localDateKey, foodCatalogSize } from './src/domain';
import type { AppData, DayCheckIn, Level, Meal, PatternResult, SymptomDefinition, SymptomLog } from './src/domain/types';
import { LEARN_ARTICLES, SAFETY_NOTICES, type LearnArticle } from './src/content';
import { emptyDiary, parseDiary, type SavedDiary } from './src/storage/schema';
import { loadDiary, saveDiary } from './src/storage/persistence';
import { exportFile, importFile } from './src/services/files';

type Tab = 'journal' | 'patterns' | 'learn' | 'you';
type ModalState = { type: 'meal'; meal?: Meal; mode?: 'type' | 'scan' } | { type: 'symptom'; symptom?: SymptomLog } | { type: 'symptoms' } | { type: 'checkin' } | { type: 'article'; article: LearnArticle } | { type: 'pattern'; pattern: PatternResult } | { type: 'welcome' } | { type: 'privacy' } | { type: 'delete' } | { type: 'restore'; diary: SavedDiary } | null;
const tabs = [{ id: 'journal', label: 'My journal', icon: BookOpen }, { id: 'patterns', label: 'My patterns', icon: TrendingUp }, { id: 'learn', label: 'Discover', icon: Sprout }, { id: 'you', label: 'My space', icon: Settings2 }] as const;
const dateLabel = (date: string, options: Intl.DateTimeFormatOptions) => new Date(date.length === 10 ? `${date}T12:00:00` : date).toLocaleDateString('en-GB', options);
const timeLabel = (date: string) => new Date(date).toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' });
const percent = (value: number) => `${Math.round(value * 100)}%`;
const moveDay = (date: string, n: number) => { const d = new Date(`${date}T12:00:00`); d.setDate(d.getDate() + n); return localDateKey(d); };

export default function App() {
  const [loaded, error] = useFonts({ DMSans_400Regular, DMSans_500Medium, DMSans_600SemiBold, DMSans_700Bold, Lora_400Regular, Lora_500Medium });
  if (!loaded && !error) return <View style={{ flex: 1, backgroundColor: C.bg, justifyContent: 'center', alignItems: 'center' }}><ActivityIndicator color={C.green} /></View>;
  return <SafeAreaProvider><Bellywise /></SafeAreaProvider>;
}

function Bellywise() {
  const { width } = useWindowDimensions(); const wide = width >= 1000; const twoCols = width >= 760;
  const insets = useSafeAreaInsets();
  const [tab, setTab] = useState<Tab>('journal');
  const [saved, setSaved] = useState<SavedDiary | null>(null);
  const savedRef = useRef<SavedDiary>(emptyDiary());
  const [demo, setDemo] = useState<SavedDiary | null>(null);
  const demoRef = useRef<SavedDiary | null>(null);
  const queue = useRef(Promise.resolve());
  const [loadError, setLoadError] = useState('');
  const [notice, setNotice] = useState('');
  const [modal, setModal] = useState<ModalState>(null);
  const [selectedDay, setSelectedDay] = useState(localDateKey(new Date()));
  const [weekEnd, setWeekEnd] = useState(localDateKey(new Date()));
  const [journalFilter, setJournalFilter] = useState('All entries');
  const [search, setSearch] = useState('');
  const [patternKind, setPatternKind] = useState<'negative' | 'positive'>('negative');
  const [learnCategory, setLearnCategory] = useState('All');
  const scroll = useRef<ScrollView>(null);
  useEffect(() => { loadDiary().then(value => { savedRef.current = value; setSaved(value); if (!value.welcomed) setModal({ type: 'welcome' }); }).catch(e => setLoadError(e instanceof Error ? e.message : 'Your diary could not be opened.')); }, []);
  useEffect(() => { scroll.current?.scrollTo({ y: 0, animated: false }); setSearch(''); }, [tab]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(''), 6000); return () => clearTimeout(timer); }, [notice]);
  const active = demo || saved || emptyDiary();
  const data = active.data;
  const definitions = useMemo(() => [...BUILT_IN_SYMPTOMS, ...data.customSymptoms], [data.customSymptoms]);
  const analysis = useMemo(() => analyzePatterns(data), [data]);
  const patterns = analysis.patterns.filter(p => p.symptomKind === patternKind && p.riskDifference > 0).slice(0, 12);
  const today = localDateKey(new Date());
  const commit = (transform: (state: SavedDiary) => SavedDiary): Promise<void> => {
    const inDemo = demoRef.current !== null;
    const operation = queue.current.then(async () => {
      const current = inDemo ? demoRef.current : savedRef.current;
      if (!current) throw new Error('The example diary has closed. Please try again.');
      const next = transform(current);
      if (inDemo) { demoRef.current = next; setDemo(next); }
      else { await saveDiary(next); savedRef.current = next; setSaved(next); }
    });
    queue.current = operation.catch(() => {});
    return operation;
  };
  const changeData = (fn: (d: AppData) => AppData) => commit(s => ({ ...s, data: fn(s.data) }));
  const run = async (action: () => Promise<void>, message?: string) => { try { await action(); if (message) setNotice(message); } catch (e) { setNotice(e instanceof Error ? e.message : 'Something went wrong. Please try again.'); } };
  const startDemo = () => { const example = { ...emptyDiary(), welcomed: true, selectedSymptoms: BUILT_IN_SYMPTOMS.map(s => s.id), data: getDemoData() }; demoRef.current = example; setDemo(example); setModal(null); setSelectedDay(moveDay(today, -1)); setTab('journal'); };
  const exitDemo = () => { demoRef.current = null; setDemo(null); setSelectedDay(today); setWeekEnd(today); setNotice('Your personal diary is ready. The example entries were kept separate.'); };
  const mealEntries = data.meals.filter(m => localDateKey(new Date(m.eatenAt)) === selectedDay);
  const symptomEntries = data.symptoms.filter(s => localDateKey(new Date(s.occurredAt)) === selectedDay);
  const selectedCheckIn = data.checkIns.find(c => c.date === selectedDay);
  const allEntries = [
    ...mealEntries.map(m => ({ type: 'meal' as const, time: m.eatenAt, name: m.name, value: m })),
    ...symptomEntries.map(s => ({ type: 'symptom' as const, time: s.occurredAt, name: definitions.find(d => d.id === s.symptomId)?.name || 'Feeling', value: s })),
  ].filter(e => (journalFilter === 'All entries' || (journalFilter === 'Food' ? e.type === 'meal' && e.value.kind !== 'drink' : journalFilter === 'Drinks' ? e.type === 'meal' && e.value.kind === 'drink' : e.type === 'symptom')) && e.name.toLowerCase().includes(search.toLowerCase())).sort((a, b) => a.time.localeCompare(b.time));
  const trackedDays = new Set(data.meals.map(m => localDateKey(new Date(m.eatenAt)))).size;
  const weeklyValues = Array.from({ length: 7 }, (_, i) => data.symptoms.filter(s => localDateKey(new Date(s.occurredAt)) === moveDay(selectedDay, i - 6) && definitions.find(d => d.id === s.symptomId)?.kind === 'negative').reduce((max, s) => Math.max(max, s.severity), 0));

  if (!saved) return <View style={{ flex: 1, backgroundColor: C.bg, justifyContent: 'center', padding: 30, alignItems: 'center', gap: 20 }}><Leaf size={38} color={C.green} /><Heading>Bellywise</Heading>{loadError ? <><Notice warm>{loadError} Your saved data has not been replaced.</Notice><Button label="Try opening again" onPress={() => { setLoadError(''); loadDiary().then(v => { savedRef.current = v; setSaved(v); }).catch(e => setLoadError(e.message)); }} /></> : <ActivityIndicator color={C.green} />}</View>;

  const nav = (mobile = false) => tabs.map(item => <Pressable key={item.id} accessibilityRole="tab" accessibilityState={{ selected: tab === item.id }} accessibilityLabel={item.label} onPress={() => setTab(item.id)} style={({ pressed }) => mobile ? { flex: 1, alignItems: 'center', gap: 5, paddingVertical: 10, opacity: pressed ? 0.5 : 1 } : { flexDirection: 'row', alignItems: 'center', gap: 14, padding: 15, paddingHorizontal: 19, borderRadius: 12, backgroundColor: tab === item.id ? '#E8F0DB' : 'transparent', opacity: pressed ? 0.5 : 1 }}><item.icon color={mobile ? tab === item.id ? C.green : C.muted : tab === item.id ? C.green : '#C3D1C5'} size={mobile ? 21 : 20} strokeWidth={1.7} /><T style={{ fontSize: mobile ? 10 : 13, fontFamily: tab === item.id ? F.semi : F.regular, color: mobile ? tab === item.id ? C.green : C.muted : tab === item.id ? C.green : '#C3D1C5' }}>{mobile ? ({ journal: 'Journal', patterns: 'Patterns', learn: 'Discover', you: 'My space' }[item.id]) : item.label}</T>{!mobile && tab === item.id && <View style={{ marginLeft: 'auto', width: 5, height: 5, borderRadius: 3, backgroundColor: C.green }} />}</Pressable>);

  return <View style={{ flex: 1, flexDirection: 'row', backgroundColor: C.bg }}><StatusBar barStyle="dark-content" />
    {wide && <View style={{ width: 232, backgroundColor: '#243F32', paddingHorizontal: 21, paddingTop: 38, paddingBottom: 26 }}><Row style={{ gap: 10, paddingHorizontal: 10 }}><Leaf size={25} color="#D8E8BE" strokeWidth={1.4} /><Heading size={27} style={{ color: '#F4F4E9', letterSpacing: -1.2 }}>bellywise</Heading></Row><T style={{ color: '#93AA97', fontSize: 10, letterSpacing: 1.6, marginLeft: 45, marginTop: 7 }}>FOOD. FEELINGS. YOU.</T><View style={{ marginTop: 56, gap: 9 }}>{nav()}</View><View style={{ flex: 1 }} /><View style={{ padding: 18, backgroundColor: '#304D3D', borderRadius: 18, gap: 12 }}><Sprout size={27} color="#D9E7BF" strokeWidth={1.4} /><T style={{ color: '#F0F2E8', fontFamily: F.serif, fontSize: 18, lineHeight: 26 }}>Small notes. Meaningful discoveries.</T><T style={{ fontSize: 11, lineHeight: 18, color: '#B4C4B6' }}>Get to know your body, one day at a time.</T></View><Row style={{ gap: 8, marginTop: 24, justifyContent: 'center' }}><LockKeyhole size={12} color="#93AA97" /><T style={{ color: '#93AA97', fontSize: 10 }}>Your journal stays yours</T></Row></View>}
    <View style={{ flex: 1 }}>
      <View style={{ paddingHorizontal: wide ? 40 : 22, paddingTop: wide ? 24 : Math.max(insets.top, 18), paddingBottom: 18, borderBottomWidth: 1, borderBottomColor: C.line, backgroundColor: C.bg }}><Row style={{ justifyContent: 'space-between' }}>{wide ? <Row style={{ gap: 8 }}><T muted style={{ fontSize: 12 }}>Your space</T><ChevronRight size={12} color={C.muted} /><T style={{ fontSize: 12 }}>{tabs.find(t => t.id === tab)?.label}</T></Row> : <Row style={{ gap: 7 }}><Leaf size={21} color={C.green} strokeWidth={1.5} /><Heading size={25}>bellywise</Heading></Row>}<Row style={{ gap: 8 }}>{wide && <T muted style={{ fontSize: 12 }}>{dateLabel(today, { weekday: 'short', day: 'numeric', month: 'long' })}</T>}<Pressable accessibilityRole="button" accessibilityLabel="Open my space" onPress={() => setTab('you')} style={{ width: 35, height: 35, borderRadius: 18, backgroundColor: C.lime, justifyContent: 'center', alignItems: 'center' }}><Flower2 size={19} color={C.green} strokeWidth={1.5} /></Pressable></Row></Row></View>
      {demo && <Row style={{ backgroundColor: '#F3E9D5', paddingHorizontal: wide ? 40 : 16, paddingVertical: 9, justifyContent: 'space-between' }}><T style={{ fontSize: 11, color: '#85643A', flex: 1 }}>EXAMPLE DIARY · These are fictional entries</T><Pressable accessibilityRole="button" onPress={exitDemo} style={{ padding: 5 }}><T style={{ fontSize: 11, color: '#85643A', fontFamily: F.semi }}>Exit demo</T></Pressable></Row>}
      <ScrollView ref={scroll} showsVerticalScrollIndicator={false} contentContainerStyle={{ padding: wide ? 40 : 22, paddingTop: wide ? 32 : 26, paddingBottom: 36, maxWidth: 1390, width: '100%', alignSelf: 'center' }}>
        {tab === 'journal' && <>
          <Row style={{ justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 28 }}><View style={{ flex: 1 }}><T style={s.eyebrow}>YOUR EVERYDAY, A LITTLE CLEARER</T><Heading size={wide ? 35 : 29} style={{ marginTop: 8 }}>Let’s connect the dots.</Heading><T muted style={{ marginTop: 8, fontSize: 13 }}>What you eat and drink. How you feel. A little more understanding.</T></View>{wide && <Button label="Log food / drink" icon={Plus} onPress={() => setModal({ type: 'meal' })} />}</Row>
          <View style={{ flexDirection: twoCols ? 'row' : 'column', gap: 25 }}>
            <View style={{ flex: 1, minWidth: 0, gap: 26 }}>
              <View style={{ borderRadius: 24, backgroundColor: '#E7EEDC', padding: wide ? 28 : 22, minHeight: 204, overflow: 'hidden' }}><View style={{ maxWidth: '74%', zIndex: 1 }}><Row style={{ gap: 6 }}><Sun size={14} color={C.green} /><T style={{ fontSize: 10, color: C.green, letterSpacing: 1.1, fontFamily: F.semi }}>A LITTLE CHECK-IN</T></Row><Heading size={wide ? 29 : 25} style={{ marginTop: 12 }}>Every body has{ '\n'}a story. Notice yours.</Heading><T style={{ marginTop: 10, color: '#69805D', fontSize: 12, maxWidth: 255 }}>Start with food, a drink or a feeling.{ '\n'}The understanding comes with time.</T></View><View style={{ position: 'absolute', right: -24, bottom: -27, opacity: 0.95 }}><Botanical size={wide ? 218 : 168} light /></View></View>
              <Row style={{ gap: 12 }}><Button label="Log food / drink" icon={Utensils} onPress={() => setModal({ type: 'meal' })} style={{ flex: 1 }} /><Button label="Log a feeling" icon={Smile} variant="secondary" onPress={() => setModal({ type: 'symptom' })} style={{ flex: 1 }} /><IconButton icon={Camera} label="Scan an ingredient label" onPress={() => setModal({ type: 'meal', mode: 'scan' })} /></Row>
              <View><Row style={{ justifyContent: 'space-between', marginBottom: 13 }}><Row style={{ gap: 8 }}><CalendarDays size={17} color={C.green} /><T style={{ fontFamily: F.semi, fontSize: 14 }}>{dateLabel(selectedDay, { month: 'long', year: 'numeric' })}</T></Row><Row style={{ gap: 0 }}><IconButton icon={ChevronLeft} label="Previous week" onPress={() => setWeekEnd(moveDay(weekEnd, -7))} /><Pressable accessibilityRole="button" onPress={() => { setSelectedDay(today); setWeekEnd(today); }} style={{ padding: 8 }}><T style={{ fontSize: 11, color: C.green }}>Today</T></Pressable><IconButton icon={ChevronRight} label="Next week" onPress={() => setWeekEnd(moveDay(weekEnd, 7) > today ? today : moveDay(weekEnd, 7))} /></Row></Row>
                <Row style={{ justifyContent: 'space-between', gap: 6 }}>{Array.from({ length: 7 }, (_, i) => moveDay(weekEnd, i - 6)).map(day => { const selected = day === selectedDay; const hasEntries = data.meals.some(m => localDateKey(new Date(m.eatenAt)) === day) || data.symptoms.some(s => localDateKey(new Date(s.occurredAt)) === day); return <Pressable accessibilityRole="button" accessibilityLabel={dateLabel(day, { weekday: 'long', day: 'numeric', month: 'long' })} accessibilityState={{ selected }} key={day} onPress={() => setSelectedDay(day)} style={{ flex: 1, alignItems: 'center', gap: 8, paddingTop: 13, paddingBottom: 10, backgroundColor: selected ? C.green : 'transparent', borderRadius: 15 }}><T style={{ fontSize: 10, color: selected ? '#B7CCB4' : C.muted }}>{dateLabel(day, { weekday: 'short' })}</T><T style={{ fontSize: 17, fontFamily: F.medium, color: selected ? '#fff' : C.ink }}>{Number(day.slice(-2))}</T><View style={{ width: 4, height: 4, borderRadius: 2, backgroundColor: hasEntries ? selected ? '#D6E6BD' : C.green : 'transparent' }} /></Pressable>; })}</Row>
              </View>
              <View><SectionTitle title={selectedDay === today ? 'Today’s journal' : dateLabel(selectedDay, { weekday: 'long', day: 'numeric', month: 'short' })} action={`${allEntries.length} entries`} /><Row style={{ gap: 8, marginBottom: 17 }}>{['All entries', 'Food', 'Drinks', 'Feelings'].map(f => <Chip key={f} label={f} selected={journalFilter === f} onPress={() => setJournalFilter(f)} />)}</Row>{data.meals.length + data.symptoms.length > 10 && <View style={{ marginBottom: 15 }}><Field value={search} onChangeText={setSearch} placeholder="Search this day’s journal" /></View>}
                {allEntries.length === 0 ? <Card style={{ alignItems: 'center', paddingVertical: 34, gap: 12 }}><View style={{ padding: 14, borderRadius: 25, backgroundColor: C.pale }}><BookOpen color={C.green} size={22} strokeWidth={1.4} /></View><Heading size={21}>A fresh page for your day</Heading><T muted style={{ textAlign: 'center', fontSize: 12, maxWidth: 280 }}>Start with what you ate or how you felt. Even a small note is a useful beginning.</T><Button label="Add your first note" icon={Plus} variant="ghost" onPress={() => setModal({ type: 'meal' })} /></Card> : <View style={{ gap: 11 }}>{allEntries.map(entry => { const isMeal = entry.type === 'meal'; const positive = !isMeal && definitions.find(d => d.id === entry.value.symptomId)?.kind === 'positive'; const Icon = isMeal ? entry.value.kind === 'drink' || /coffee|latte|tea/i.test(entry.name) ? Coffee : Utensils : positive ? Sun : Heart; const color = isMeal ? C.green : positive ? '#81704B' : '#946E81'; return <Pressable key={entry.value.id} accessibilityRole="button" accessibilityLabel={`Edit ${entry.name}`} onPress={() => setModal(isMeal ? { type: 'meal', meal: entry.value } : { type: 'symptom', symptom: entry.value })} style={({ pressed }) => ({ padding: 18, borderWidth: 1, borderColor: C.line, borderRadius: 18, backgroundColor: C.paper, opacity: pressed ? 0.7 : 1 })}><Row style={{ alignItems: 'flex-start' }}><View style={{ width: 44, height: 44, borderRadius: 14, backgroundColor: isMeal ? '#EEF0E4' : positive ? '#F7EEDB' : C.lilac, alignItems: 'center', justifyContent: 'center' }}><Icon color={color} size={21} strokeWidth={1.5} /></View><View style={{ flex: 1 }}><Row style={{ justifyContent: 'space-between', gap: 5 }}><T style={{ fontFamily: F.semi, fontSize: 14, flex: 1 }}>{entry.name}</T><T muted style={{ fontSize: 10 }}>{timeLabel(entry.time)}</T></Row>{isMeal ? <><T muted numberOfLines={2} style={{ fontSize: 11, marginTop: 3 }}>{entry.value.ingredients.map(x => x.name).join(' · ') || 'Ingredients not recorded'}</T><Row style={{ gap: 5, marginTop: 8 }}><View style={{ width: 5, height: 5, borderRadius: 3, backgroundColor: entry.value.ingredients.every(i => i.confidence === 'confirmed') && entry.value.ingredients.length ? '#729966' : '#C9AA74' }} /><T muted style={{ fontSize: 10 }}>{entry.value.ingredients.length && entry.value.ingredients.every(i => i.confidence === 'confirmed') ? 'Ingredients confirmed' : 'Includes ingredient estimates'}</T></Row></> : <Row style={{ gap: 5, marginTop: 9 }}>{[1, 2, 3, 4, 5].map(v => <View key={v} style={{ width: 8, height: 8, borderRadius: 4, backgroundColor: v <= entry.value.severity ? color : C.line }} />)}<T muted style={{ fontSize: 10, marginLeft: 6 }}>{positive ? 'Positive feeling' : ['Slight', 'Mild', 'Moderate', 'Strong', 'Very strong'][entry.value.severity - 1]}</T></Row>}</View></Row></Pressable>; })}</View>}
              </View>
              <Row style={{ justifyContent: 'center', gap: 6 }}><Leaf size={12} color={C.muted} /><T muted style={{ fontSize: 10 }}>Curiosity over restriction. Progress over perfection.</T></Row>
            </View>
            <View style={{ width: twoCols ? wide ? 310 : 270 : undefined, gap: 22 }}>
              <Card style={{ padding: 22 }}><Row style={{ justifyContent: 'space-between', marginBottom: 18 }}><T style={{ fontFamily: F.semi }}>Your journey so far</T><Sprout color={C.green} size={18} /></Row><Row style={{ justifyContent: 'space-between', marginBottom: 20 }}>{[{ value: trackedDays, label: 'days noted' }, { value: data.meals.length, label: 'food & drink' }, { value: data.symptoms.length, label: 'feelings' }].map(stat => <View key={stat.label}><Heading size={27}>{stat.value}</Heading><T muted style={{ fontSize: 10, marginTop: 5 }}>{stat.label}</T></View>)}</Row><View style={{ height: 1, backgroundColor: C.line, marginBottom: 18 }} /><Row style={{ gap: 8 }}><View style={{ width: 7, height: 7, borderRadius: 4, backgroundColor: '#99B278' }} /><T style={{ fontSize: 11, color: C.green }}>{analysis.completeDays >= 14 ? 'Your diary is building context' : 'Getting to know your patterns'}</T></Row><View style={{ height: 5, backgroundColor: C.pale, borderRadius: 3, marginVertical: 12 }}><View style={{ height: 5, width: `${Math.min(100, analysis.completeDays / 14 * 100)}%`, backgroundColor: '#97AF76', borderRadius: 3 }} /></View><T muted style={{ fontSize: 11 }}>{Math.min(analysis.completeDays, 14)} of 14 complete days to start exploring. Each food also needs enough days with and without it.</T></Card>
              <Card style={{ backgroundColor: '#F3EEE6', borderColor: '#EBE3D8', padding: 22 }}><Row style={{ justifyContent: 'space-between', marginBottom: 12 }}><Pill label="THE BIGGER PICTURE" color="#8B704E" background="#EAE1D3" /><Sparkles size={17} color="#9B825B" /></Row><Heading size={22}>How was your day?</Heading><T muted style={{ marginVertical: 12, fontSize: 12 }}>Sleep and stress can affect how you feel, too. A complete diary helps us make fairer comparisons.</T><Button label={selectedCheckIn?.complete ? 'Review day’s check-in' : 'Complete a daily check-in'} icon={selectedCheckIn?.complete ? Check : Plus} variant="secondary" style={{ backgroundColor: '#E8E0D1' }} onPress={() => setModal({ type: 'checkin' })} /></Card>
              <Card style={{ padding: 22 }}><SectionTitle title="A little food for thought" /><View style={{ height: 100, backgroundColor: C.lilac, borderRadius: 13, marginBottom: 16, alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }}><Row style={{ gap: 21 }}><View style={{ backgroundColor: '#FCFAF6', padding: 16, borderRadius: 50 }}><Utensils color="#7C7E92" size={29} strokeWidth={1.2} /></View><View style={{ width: 36, height: 1, backgroundColor: '#B8B5CB' }} /><Heart size={38} color="#92839C" strokeWidth={1.1} /></Row></View><T style={{ fontFamily: F.semi, fontSize: 14 }}>A pattern is a starting point</T><T muted style={{ fontSize: 11, marginTop: 7, marginBottom: 12 }}>Learn what your diary can tell you, and what it can’t.</T><Button label="Understand your patterns" icon={ArrowUpRight} variant="ghost" onPress={() => { setTab('learn'); setModal({ type: 'article', article: LEARN_ARTICLES.find(a => a.id.includes('pattern') || a.id.includes('correl')) || LEARN_ARTICLES[0] }); }} /></Card>
            </View>
          </View>
        </>}
        {tab === 'patterns' && <>
          <T style={s.eyebrow}>A LITTLE MORE UNDERSTANDING</T><Heading style={{ marginTop: 8 }}>Your body, in context.</Heading><T muted style={{ marginTop: 10, marginBottom: 26 }}>Explore associations in your journal. Every finding is a question to investigate.</T>
          <Card style={{ backgroundColor: C.pale, marginBottom: 24 }}><Row style={{ alignItems: 'flex-start' }}><Sparkles size={24} color={C.green} /><View style={{ flex: 1 }}><T style={{ fontFamily: F.semi }}>{analysis.completeDays < 14 ? 'Good patterns start with a fuller picture' : 'You’re building a useful picture'}</T><T muted style={{ fontSize: 12, marginTop: 7 }}>{analysis.message}</T><T style={{ fontSize: 11, color: C.green, marginTop: 10 }}>{analysis.completeDays} complete past days · at least 6 days with and 6 without each ingredient</T></View></Row></Card>
          <Row style={{ marginBottom: 24 }}><Chip label="Symptoms" selected={patternKind === 'negative'} onPress={() => setPatternKind('negative')} /><Chip label="Positive feelings" selected={patternKind === 'positive'} onPress={() => setPatternKind('positive')} /></Row>
          {patterns.length === 0 ? <Card style={{ alignItems: 'center', paddingVertical: 46, gap: 16 }}><TrendingUp color={C.green} size={36} strokeWidth={1.3} /><Heading size={24}>Give your story a little time</Heading><T muted style={{ maxWidth: 450, textAlign: 'center' }}>Log meals, feelings and complete days—including uneventful days. We’ll show comparisons when there are relevant observations.</T><Button label="Back to my journal" variant="secondary" onPress={() => setTab('journal')} /></Card> : <View style={{ flexDirection: twoCols ? 'row' : 'column', flexWrap: 'wrap', gap: 18 }}>{patterns.map(p => <Pressable key={p.id} accessibilityRole="button" accessibilityLabel={`View ${p.ingredientName} and ${p.symptomName}`} onPress={() => setModal({ type: 'pattern', pattern: p })} style={{ width: twoCols ? '48.5%' : '100%' }}><Card><Row style={{ justifyContent: 'space-between' }}><Pill label={p.status === 'emerging' ? 'Worth a closer look' : p.status === 'exploratory' ? 'Early observation' : 'More data needed'} color={p.status === 'emerging' ? C.green : '#92794D'} background={p.status === 'emerging' ? C.pale : '#F6EFDF'} /><ArrowUpRight size={18} color={C.muted} /></Row><Heading size={24} style={{ marginTop: 19 }}>{p.ingredientName}</Heading><T muted style={{ marginTop: 5, marginBottom: 22 }}>{p.symptomName} · {p.windowLabel}</T>{[{ label: 'Days with this ingredient', rate: p.exposedRate, n: p.exposedDays, hits: p.exposedSymptomDays, color: C.green }, { label: 'Days without it', rate: p.unexposedRate, n: p.unexposedDays, hits: p.unexposedSymptomDays, color: '#B6C4AA' }].map(r => <View key={r.label} style={{ marginBottom: 13 }}><Row style={{ justifyContent: 'space-between', marginBottom: 8 }}><T style={{ fontSize: 11 }}>{r.label}</T><T style={{ fontFamily: F.semi, fontSize: 12 }}>{r.hits}/{r.n}</T></Row><View style={{ height: 7, backgroundColor: C.pale, borderRadius: 5 }}><View style={{ width: `${r.rate * 100}%`, backgroundColor: r.color, height: 7, borderRadius: 5 }} /></View></View>)}<T muted style={{ fontSize: 10, marginTop: 8 }}>Days when this feeling was logged. Tap for uncertainty, estimates and foods eaten together.</T></Card></Pressable>)}</View>}
          <View style={{ marginTop: 26 }}><Notice>These are exploratory associations, not diagnoses or food-safety advice. Multiple comparisons and repeated days can produce chance patterns. Do not remove food groups based on this screen alone.</Notice></View>
          <Button label="How the analysis works" variant="ghost" icon={CircleHelp} onPress={() => setModal({ type: 'article', article: LEARN_ARTICLES.find(a => a.id.includes('pattern') || a.id.includes('correl')) || LEARN_ARTICLES[0] })} />
        </>}
        {tab === 'learn' && <>
          <T style={s.eyebrow}>KNOWLEDGE, WITHOUT THE OVERWHELM</T><Heading style={{ marginTop: 8 }}>A gentler way to understand.</Heading><T muted style={{ marginTop: 10, marginBottom: 25 }}>Clear, sourced guides to food, digestion and your next steps.</T>
          <View style={{ flexDirection: twoCols ? 'row' : 'column', backgroundColor: '#E8EEDD', borderRadius: 23, padding: 26, marginBottom: 28, alignItems: twoCols ? 'center' : 'flex-start' }}><View style={{ flex: 1 }}><Pill label="START HERE" background="#D7E3C4" /><Heading size={27} style={{ marginTop: 16 }}>Listen to your body.{ '\n'}Keep an open mind.</Heading><T style={{ color: '#6E805E', marginTop: 12, maxWidth: 470, fontSize: 13 }}>A food diary can help you ask better questions. Understanding the difference between an intolerance and an allergy is a good place to begin.</T><Button label="Read the guide" icon={ArrowRight} variant="ghost" style={{ alignSelf: 'flex-start', paddingLeft: 0, marginTop: 10 }} onPress={() => setModal({ type: 'article', article: LEARN_ARTICLES[0] })} /></View>{twoCols && <Botanical size={195} />}</View>
          <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={{ gap: 8, paddingBottom: 22 }}>{['All', ...new Set(LEARN_ARTICLES.map(a => a.category))].map(c => <Chip key={c} label={c} selected={learnCategory === c} onPress={() => setLearnCategory(c)} />)}</ScrollView>
          <View style={{ flexDirection: twoCols ? 'row' : 'column', flexWrap: 'wrap', gap: 18 }}>{LEARN_ARTICLES.filter(a => learnCategory === 'All' || a.category === learnCategory).map((a, i) => <Pressable accessibilityRole="button" accessibilityLabel={`Read ${a.title}`} key={a.id} onPress={() => setModal({ type: 'article', article: a })} style={{ width: twoCols ? '48.5%' : '100%' }}><Card style={{ height: '100%', padding: 23 }}><Row style={{ justifyContent: 'space-between', marginBottom: 16 }}><View style={{ width: 43, height: 43, borderRadius: 14, backgroundColor: [C.pale, C.lilac, C.peach][i % 3], alignItems: 'center', justifyContent: 'center' }}>{i % 3 === 0 ? <Leaf size={21} color={C.green} /> : i % 3 === 1 ? <BookOpen size={21} color="#8C7C93" /> : <Sun size={21} color={C.orange} />}</View><T muted style={{ fontSize: 10 }}>{a.readMinutes} min read</T></Row><T style={{ fontSize: 10, color: C.green, textTransform: 'uppercase', letterSpacing: 1 }}>{a.category}</T><Heading size={21} style={{ marginTop: 8 }}>{a.title}</Heading><T muted style={{ fontSize: 12, marginTop: 10, flex: 1 }}>{a.subtitle}</T><Row style={{ marginTop: 17, gap: 5 }}><T style={{ fontSize: 11, fontFamily: F.semi, color: C.green }}>Read more</T><ArrowUpRight size={13} color={C.green} /></Row></Card></Pressable>)}</View>
        </>}
        {tab === 'you' && <>
          <T style={s.eyebrow}>MADE PERSONAL</T><Heading style={{ marginTop: 8 }}>Your journal. Your choices.</Heading><T muted style={{ marginTop: 10, marginBottom: 28 }}>Make Bellywise work for you, and keep control of your data.</T>
          <View style={{ gap: 18 }}><Card><Row style={{ marginBottom: 14 }}><Heart size={22} color={C.green} /><T style={{ fontFamily: F.semi, fontSize: 16 }}>What would you like to track?</T></Row><T muted style={{ marginBottom: 18 }}>Choose built-in symptoms and positive feelings, or add your own. You’re currently tracking {active.selectedSymptoms.length}.</T><Button label="Personalise my symptoms" variant="secondary" onPress={() => setModal({ type: 'symptoms' })} /></Card>
            <Card><Row style={{ marginBottom: 14 }}><ShieldCheck size={22} color={C.green} /><T style={{ fontFamily: F.semi, fontSize: 16 }}>Private by design</T></Row><T muted style={{ marginBottom: 15 }}>{Platform.OS === 'web' ? 'This browser preview stores its diary in this browser, without database encryption. Use fictional data here. The iOS app uses encrypted on-device storage.' : 'Your diary is encrypted on this device. Bellywise has no diary server, advertising SDK or analytics. Keep an exported backup if you need to move phones.'}</T><Button label="Privacy & data details" variant="ghost" icon={ArrowUpRight} onPress={() => setModal({ type: 'privacy' })} /></Card>
            <Card><Row style={{ marginBottom: 14 }}><ArrowDownToLine size={22} color={C.green} /><T style={{ fontFamily: F.semi, fontSize: 16 }}>Take your story with you</T></Row><T muted style={{ marginBottom: 18 }}>Export a readable report for a healthcare professional, or save a backup to restore later. Exports contain your diary and are not encrypted.</T><Row style={{ flexWrap: 'wrap' }}><Button label="Export a report" icon={ArrowDownToLine} variant="secondary" onPress={() => run(() => exportFile(createReport(data, definitions, analysis.patterns, !!demo), 'Bellywise-diary-report.txt', 'text/plain'), 'Your report is ready to save or share.')} /><Button label="Save backup" icon={ArrowDownToLine} variant="ghost" onPress={() => run(() => exportFile(JSON.stringify(active, null, 2), 'Bellywise-backup.json'), 'Your backup is ready. Keep it somewhere private.')} /><Button label="Restore backup" icon={Upload} variant="ghost" onPress={() => run(async () => { const raw = await importFile(); if (raw) setModal({ type: 'restore', diary: parseDiary(raw) }); })} /></Row></Card>
            <Card><Row style={{ marginBottom: 13 }}><Sparkles size={22} color={C.green} /><T style={{ fontFamily: F.semi, fontSize: 16 }}>Try an example diary</T></Row><T muted style={{ marginBottom: 18 }}>Explore six weeks of fictional meals and feelings. The example stays separate from your personal journal.</T><Button label={demo ? 'Return to my diary' : 'Explore example diary'} variant="secondary" onPress={demo ? exitDemo : startDemo} /></Card>
            <Card><T style={{ fontFamily: F.semi, marginBottom: 10 }}>About Bellywise</T><T muted style={{ fontSize: 12 }}>Version 1.0 · iPhone and iPad{ '\n'}{foodCatalogSize} offline foods and ingredients, plus optional Open Food Facts product search. Recipes and catalogue entries may be incomplete. Check the package you actually ate.</T><T muted style={{ fontSize: 12, marginTop: 12 }}>{SAFETY_NOTICES.general}</T><Button label="Delete my diary" variant="danger" icon={Trash2} onPress={() => setModal({ type: 'delete' })} /></Card>
          </View>
        </>}
      </ScrollView>
      {!wide && <View style={{ backgroundColor: C.paper, paddingBottom: Math.max(insets.bottom, 6), paddingTop: 3, borderTopWidth: 1, borderTopColor: C.line }}><Row style={{ gap: 0 }}>{nav(true)}</Row></View>}
      {!!notice && <Pressable accessibilityRole="alert" onPress={() => setNotice('')} style={{ position: 'absolute', left: 18, right: 18, bottom: wide ? 20 : 86, backgroundColor: C.ink, borderRadius: 14, padding: 16 }}><T style={{ color: '#fff', fontSize: 12 }}>{notice}</T></Pressable>}
    </View>
    {modal?.type === 'welcome' && <Sheet title="Welcome to Bellywise" subtitle="A little awareness. A little more you." onClose={() => run(() => commit(s => ({ ...s, welcomed: true }))).then(() => setModal(null))}><View style={{ alignItems: 'center' }}><Botanical size={155} /></View><Heading size={25}>Get curious about what{ '\n'}makes you feel like you.</Heading><T muted>Log what you eat and how you feel. Bellywise helps you explore possible connections and bring a clearer story to your healthcare professional.</T><Notice>{SAFETY_NOTICES.general}</Notice>{Platform.OS === 'web' && <Notice warm>Browser preview: use fictional entries. Camera OCR and encrypted storage are available in the native iOS build.</Notice>}<Button label="Start my journal" icon={ArrowRight} onPress={() => run(async () => { await commit(s => ({ ...s, welcomed: true })); setModal(null); })} /><Button label="Explore with example entries" variant="secondary" onPress={startDemo} /></Sheet>}
    {modal?.type === 'meal' && <MealForm initial={modal.meal} initialMode={modal.mode} onClose={() => setModal(null)} onSave={m => changeData(d => ({ ...d, meals: [...d.meals.filter(x => x.id !== m.id), m], checkIns: invalidateDays(d.checkIns, [m.eatenAt, modal.meal?.eatenAt]) })).then(() => { setSelectedDay(localDateKey(new Date(m.eatenAt))); setNotice('Food saved to your journal.'); })} onDelete={modal.meal ? () => changeData(d => ({ ...d, meals: d.meals.filter(x => x.id !== modal.meal!.id), checkIns: invalidateDays(d.checkIns, [modal.meal!.eatenAt]) })) : undefined} />}
    {modal?.type === 'symptom' && <SymptomForm initial={modal.symptom} definitions={definitions} selectedIds={active.selectedSymptoms} onManage={() => setModal({ type: 'symptoms' })} onClose={() => setModal(null)} onSave={entry => changeData(d => ({ ...d, symptoms: [...d.symptoms.filter(x => x.id !== entry.id), entry], checkIns: invalidateDays(d.checkIns, [entry.occurredAt, modal.symptom?.occurredAt]) })).then(() => { setSelectedDay(localDateKey(new Date(entry.occurredAt))); setNotice('Feeling saved to your journal.'); })} onDelete={modal.symptom ? () => changeData(d => ({ ...d, symptoms: d.symptoms.filter(x => x.id !== modal.symptom!.id), checkIns: invalidateDays(d.checkIns, [modal.symptom!.occurredAt]) })) : undefined} />}
    {modal?.type === 'symptoms' && <ManageSymptoms definitions={definitions} selected={active.selectedSymptoms} onClose={() => setModal(null)} onSave={(ids, custom) => commit(state => ({ ...state, selectedSymptoms: ids, data: { ...state.data, customSymptoms: custom } }))} />}
    {modal?.type === 'checkin' && <CheckInForm date={selectedDay} initial={selectedCheckIn} onClose={() => setModal(null)} onSave={checkin => commit(state => ({ ...state, data: { ...state.data, checkIns: [...state.data.checkIns.filter(c => c.date !== checkin.date), { ...checkin, trackedSymptomIds: [...new Set([...state.selectedSymptoms, ...state.data.symptoms.filter(entry => localDateKey(entry.occurredAt) === checkin.date).map(entry => entry.symptomId)])] }] } })).then(() => setNotice('Daily check-in saved.'))} />}
    {modal?.type === 'article' && <Sheet title={modal.article.title} subtitle={`${modal.article.category} · ${modal.article.readMinutes} min read`} onClose={() => setModal(null)}><T style={{ fontFamily: F.medium, fontSize: 16, lineHeight: 25 }}>{modal.article.subtitle}</T>{modal.article.body.map((p, i) => <T key={i} style={{ lineHeight: 25 }}>{p}</T>)}<Notice>{modal.article.takeaway}</Notice><T style={{ fontFamily: F.semi }}>Read the original guidance</T>{modal.article.sources.map(source => <Pressable key={source.url} accessibilityRole="link" onPress={() => Linking.openURL(source.url)}><Row><ArrowUpRight size={16} color={C.green} /><T style={{ color: C.green, flex: 1, fontSize: 12, textDecorationLine: 'underline' }}>{source.title}</T></Row></Pressable>)}<T muted style={{ fontSize: 10 }}>Educational content · reviewed against these sources September 2026. Not a medical assessment.</T></Sheet>}
    {modal?.type === 'pattern' && <PatternDetail pattern={modal.pattern} onClose={() => setModal(null)} />}
    {modal?.type === 'privacy' && <Sheet title="Your data belongs to you" onClose={() => setModal(null)}><Notice>{Platform.OS === 'web' ? 'Browser preview data is saved to this browser’s local storage, which is not encrypted by Bellywise.' : 'The native app stores your diary in a SQLCipher-encrypted database. Its random key is kept in the device’s secure key store.'}</Notice><T>There is no sign-in, diary server, advertising or analytics in Bellywise. Camera text recognition uses Apple Vision on your device. The temporary image is removed after processing.</T><T>When you choose to search the product catalogue, Open Food Facts receives your search term or barcode and normal connection information, such as your IP address. Your symptoms and diary are not included.</T><T>Opening an educational source uses your browser. Your browser and that website have their own privacy practices.</T><T>Reports and backup files contain private health information in plain text. Choose carefully where you save or share them. Deleting the diary cannot delete copies you exported or copies held by operating-system backups.</T><T>Keep a private export before changing devices. Bellywise has no cloud recovery service.</T><Button label="Open Food Facts privacy information" variant="ghost" icon={ArrowUpRight} onPress={() => Linking.openURL('https://world.openfoodfacts.org/privacy')} /></Sheet>}
    {modal?.type === 'delete' && <Sheet title="Delete this diary?" onClose={() => setModal(null)}><T>This removes all meals, feelings, check-ins and custom symptoms from {demo ? 'the example diary' : 'your Bellywise journal on this device'}. This cannot be undone here. Export a backup first if you need one.</T><Button label="Keep my diary" variant="secondary" onPress={() => setModal(null)} /><Button label="Delete all diary entries" variant="danger" icon={Trash2} onPress={() => run(async () => { await commit(() => ({ ...emptyDiary(), welcomed: true })); setModal(null); setNotice('Diary entries deleted from this app. Exported copies are unchanged.'); })} /></Sheet>}
    {modal?.type === 'restore' && <Sheet title="Restore this backup?" onClose={() => setModal(null)}><T>This backup contains {modal.diary.data.meals.length} food entries, {modal.diary.data.symptoms.length} feelings and {modal.diary.data.checkIns.length} check-ins. Restoring replaces {demo ? 'the example diary' : 'your current diary'}. Save a backup of your current entries first if needed.</T><Button label="Restore and replace current diary" icon={Upload} onPress={() => run(async () => { const restored = modal.diary; await commit(() => ({ ...restored, welcomed: true })); setModal(null); setNotice('Your backup was restored.'); })} /><Button label="Cancel" variant="ghost" onPress={() => setModal(null)} /></Sheet>}
  </View>;
}

function invalidateDays(checkIns: DayCheckIn[], dates: (string | undefined)[]) {
  const keys = dates.filter(Boolean).map(d => localDateKey(new Date(d!)));
  return checkIns.map(c => keys.includes(c.date) ? { ...c, complete: false } : c);
}

function ManageSymptoms({ definitions, selected, onClose, onSave }: { definitions: SymptomDefinition[]; selected: string[]; onClose: () => void; onSave: (ids: string[], custom: SymptomDefinition[]) => Promise<void> }) {
  const [ids, setIds] = useState(selected); const [custom, setCustom] = useState(definitions.filter(d => !BUILT_IN_SYMPTOMS.some(b => b.id === d.id))); const [name, setName] = useState(''); const [kind, setKind] = useState<'negative' | 'positive'>('negative'); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  return <Sheet title="Make it your journal" subtitle="Choose the feelings you’d like to track." onClose={onClose}>{(['negative', 'positive'] as const).map(k => <View key={k} style={{ gap: 11 }}><T style={{ fontFamily: F.semi }}>{k === 'negative' ? 'Symptoms' : 'Positive feelings'}</T><View style={{ flexDirection: 'row', flexWrap: 'wrap', gap: 8 }}>{[...BUILT_IN_SYMPTOMS, ...custom].filter(d => d.kind === k).map(d => <Chip key={d.id} label={d.name} selected={ids.includes(d.id)} onPress={() => setIds(v => v.includes(d.id) ? v.filter(i => i !== d.id) : [...v, d.id])} />)}</View></View>)}<T style={{ fontFamily: F.semi }}>Add your own</T><Field label="Feeling name" value={name} onChangeText={setName} placeholder="e.g. Restless sleep" maxLength={80} /><Row><Chip label="Symptom" selected={kind === 'negative'} onPress={() => setKind('negative')} /><Chip label="Positive" selected={kind === 'positive'} onPress={() => setKind('positive')} /></Row><Button label="Add custom feeling" variant="secondary" icon={Plus} onPress={() => { if (!name.trim()) return; if ([...BUILT_IN_SYMPTOMS, ...custom].some(d => d.name.toLowerCase() === name.trim().toLowerCase())) { setError('That feeling already exists. Select it above.'); return; } const d = { id: `custom-${uid()}`, name: name.trim(), kind }; setCustom(v => [...v, d]); setIds(v => [...v, d.id]); setName(''); setError(''); }} /><T muted style={{ fontSize: 11 }}>Unselecting a feeling hides it from quick logging. Your past entries stay in your journal and analysis.</T>{!!error && <Notice warm>{error}</Notice>}<Button label="Save my choices" icon={Check} busy={busy} onPress={async () => { setBusy(true); try { await onSave(ids, custom); onClose(); } catch { setError('Your choices could not be saved.'); } finally { setBusy(false); } }} /></Sheet>;
}

function CheckInForm({ date, initial, onClose, onSave }: { date: string; initial?: DayCheckIn; onClose: () => void; onSave: (v: DayCheckIn) => Promise<void> }) {
  const [stress, setStress] = useState<Level>(initial?.stress || 2); const [sleep, setSleep] = useState(initial?.sleepHours?.toString() || ''); const [notes, setNotes] = useState(initial?.notes || ''); const [complete, setComplete] = useState(initial?.complete || false); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  return <Sheet title="The bigger picture" subtitle={dateLabel(date, { weekday: 'long', day: 'numeric', month: 'long' })} onClose={onClose}><T style={{ fontFamily: F.semi }}>How was your stress level?</T><Row style={{ flexWrap: 'wrap', gap: 8 }}>{([1, 2, 3, 4, 5] as Level[]).map(v => <Chip key={v} label={`${v} · ${['Very low', 'Low', 'Medium', 'High', 'Very high'][v - 1]}`} selected={stress === v} onPress={() => setStress(v)} />)}</Row><Field label="Hours of sleep last night (optional)" value={sleep} onChangeText={setSleep} keyboardType="decimal-pad" placeholder="e.g. 7.5" /><Field label="Context (optional)" value={notes} onChangeText={setNotes} placeholder="Illness, medication, exercise, menstrual cycle, travel…" multiline /><Notice>Only days you mark complete are used for comparisons. Include all meals, drinks and feelings—even when you felt well. Updating an entry reopens that day for review.</Notice><Row><Switch accessibilityLabel="I have logged all food and feelings for this day" value={complete} onValueChange={setComplete} trackColor={{ true: C.green }} /><T style={{ flex: 1, fontSize: 13 }}>I’ve logged all my food and feelings for this day.</T></Row>{date === localDateKey(new Date()) && <T muted style={{ fontSize: 11 }}>Today enters the analysis tomorrow, after the day has finished.</T>}{!!error && <Notice warm>{error}</Notice>}<Button label="Save daily check-in" icon={Check} busy={busy} onPress={async () => { const hours = sleep.trim() ? Number(sleep) : undefined; if (hours !== undefined && (!Number.isFinite(hours) || hours < 0 || hours > 24)) { setError('Enter sleep hours between 0 and 24.'); return; } setBusy(true); try { await onSave({ date, complete, stress, sleepHours: hours, notes }); onClose(); } catch { setError('This check-in could not be saved.'); } finally { setBusy(false); } }} /></Sheet>;
}

function PatternDetail({ pattern: p, onClose }: { pattern: PatternResult; onClose: () => void }) {
  return <Sheet title={`${p.ingredientName} & ${p.symptomName.toLowerCase()}`} subtitle={p.windowLabel} onClose={onClose}><Pill label={p.status === 'emerging' ? 'Worth a conversation' : p.status === 'exploratory' ? 'Exploratory observation' : 'Not enough data'} /><Heading size={23}>{p.headline}</Heading><T>{p.summary}</T><Card style={{ backgroundColor: C.bg }}><Row style={{ justifyContent: 'space-between' }}><View><Heading size={28}>{percent(p.exposedRate)}</Heading><T muted style={{ fontSize: 11 }}>With ingredient</T><T style={{ fontSize: 11 }}>{p.exposedSymptomDays} of {p.exposedDays} days</T></View><View><Heading size={28}>{percent(p.unexposedRate)}</Heading><T muted style={{ fontSize: 11 }}>Without ingredient</T><T style={{ fontSize: 11 }}>{p.unexposedSymptomDays} of {p.unexposedDays} days</T></View></Row></Card><T style={{ fontFamily: F.semi }}>How much uncertainty is there?</T><T>Difference: {Math.round(p.riskDifference * 100)} percentage points. The approximate 95% interval runs from {Math.round(p.interval[0] * 100)} to {Math.round(p.interval[1] * 100)} points. If it includes zero, these observations are compatible with no difference.</T><T muted style={{ fontSize: 12 }}>Multiple-comparison adjusted p-value: {p.adjustedPValue.toFixed(3)}. This is a screening statistic, not the probability you have an intolerance. Repeated observations from one person are not independent.</T><T style={{ fontFamily: F.semi }}>What could change this picture?</T>{p.cautions.map((c, i) => <Notice warm key={i}>{c}</Notice>)}<T>{p.confirmedExposedDays} exposed days include confirmed ingredients. {Math.round(p.inferredFraction * 100)}% of exposed days rely entirely on recipe estimates.</T>{p.coOccursWith.length > 0 && <Notice>Often eaten together: {p.coOccursWith.join(', ')}. These foods may explain the same signal; the diary may not be able to separate them.</Notice>}{p.lowStressRiskDifference !== undefined && <T>On lower-stress days, the difference is {Math.round(p.lowStressRiskDifference * 100)} percentage points. This is a sensitivity check, not full adjustment for stress or other influences.</T>}<T style={{ fontFamily: F.semi }}>A sensible next step</T><T>Keep logging your usual meals, including portion sizes and exact ingredients. If symptoms persist, share your diary with a GP or registered dietitian. Avoid removing multiple food groups or testing a food that has caused an allergic reaction.</T><Notice>{SAFETY_NOTICES.glutenTesting}</Notice></Sheet>;
}

function createReport(data: AppData, definitions: SymptomDefinition[], patterns: PatternResult[], demo: boolean) {
  const lines = ['BELLYWISE — FOOD & FEELINGS REPORT', demo ? 'FICTIONAL EXAMPLE DATA' : 'Personal diary export', `Exported: ${new Date().toISOString()}`, '', 'Observational diary, not a diagnosis. All ingredient sources and estimates are shown.', ''];
  const days = [...new Set([...data.meals.map(m => localDateKey(new Date(m.eatenAt))), ...data.symptoms.map(s => localDateKey(new Date(s.occurredAt))), ...data.checkIns.map(c => c.date)])].sort();
  for (const day of days) { const check = data.checkIns.find(c => c.date === day); lines.push(day, check ? `Day complete: ${check.complete ? 'yes' : 'no'}; stress ${check.stress}/5; sleep ${check.sleepHours ?? 'not recorded'} hours; ${check.notes || ''}` : 'Completeness not confirmed'); data.meals.filter(m => localDateKey(new Date(m.eatenAt)) === day).forEach(m => lines.push(`${timeLabel(m.eatenAt)} ${m.kind === 'drink' ? 'DRINK' : 'FOOD'}: ${m.name}`, `  ${m.ingredients.map(i => `${i.name} (${i.confidence})`).join(', ')}`, m.notes ? `  Notes: ${m.notes}` : '')); data.symptoms.filter(s => localDateKey(new Date(s.occurredAt)) === day).forEach(s => { const def = definitions.find(d => d.id === s.symptomId); lines.push(`${timeLabel(s.occurredAt)} ${def?.kind === 'positive' ? 'POSITIVE' : 'SYMPTOM'}: ${def?.name || s.symptomId}, intensity ${s.severity}/5. ${s.notes || ''}`); }); lines.push(''); }
  lines.push('EXPLORATORY COMPARISONS (not clinical results)');
  patterns.filter(p => p.riskDifference > 0).slice(0, 12).forEach(p => lines.push(`${p.ingredientName} / ${p.symptomName} / ${p.windowLabel}: ${p.exposedSymptomDays}/${p.exposedDays} days with versus ${p.unexposedSymptomDays}/${p.unexposedDays} without. Status: ${p.status}. Adjusted p ${p.adjustedPValue.toFixed(3)}. ${p.cautions.join(' ')}`));
  lines.push('', 'Method: complete past calendar days only; same-day co-occurrence and adjacent-day comparisons; Fisher exact tests with Benjamini–Hochberg adjustment; minimum counts; uncertainty intervals; inferred ingredient and co-occurrence cautions. The data do not establish causation.');
  return lines.join('\n');
}

const s = StyleSheet.create({ eyebrow: { fontSize: 10, fontFamily: F.semi, letterSpacing: 1.7, color: C.muted } });
